export const cardStyles = {
    container: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      padding: '10px',
    },
    box: {
      backgroundColor: '#fff',
      borderRadius: '16px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
      padding: { xs: '12px', sm: '16px' },
      width: '100%',
      maxWidth: { xs: '100%', sm: '450px' },
      height: { xs: 'auto', sm: '600px' },
      minHeight: { xs: '520px', sm: '560px' },
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      overflow: 'hidden',
      transition: 'all 0.3s ease',
      cursor: 'pointer',
      position: 'relative',
      '&:hover': {
        boxShadow: '0 8px 24px rgba(0, 0, 0, 0.18)',
      },
    },
    image: {
      width: '100%',
      height: { xs: '160px', sm: '200px' },
      objectFit: 'cover',
      borderRadius: '8px',
      mb: { xs: 2, sm: 3 },
    },
    typography: {
      title: {
        fontWeight: 'bold',
        color: '#1a1a1a',
        mb: 1.5,
        textAlign: 'center',
        fontSize: { xs: '1.1rem', sm: '1.2rem' },
        letterSpacing: '0.3px',
        lineHeight: 1.3,
      },
      subtitle: {
        color: '#333',
        mb: 2,
        textAlign: 'center',
        fontWeight: '500',
        fontSize: { xs: '0.9rem', sm: '1rem' },
        letterSpacing: '0.2px',
      },
      info: {
        color: '#444',
        fontSize: { xs: '0.9rem', sm: '0.95rem' },
        fontWeight: '500',
      },
      bankInfo: {
        color: '#444',
        fontSize: { xs: '0.85rem', sm: '0.9rem' },
      },
    },
    divider: {
      width: '60%',
      height: '2px',
      backgroundColor: 'rgba(0, 32, 91, 0.15)',
      margin: '0 auto 16px auto',
      borderRadius: '2px',
    },
    infoBox: {
      display: 'flex',
      flexDirection: 'column',
      gap: 1.5,
      backgroundColor: 'rgba(0, 32, 91, 0.03)',
      padding: { xs: '10px', sm: '12px' },
      borderRadius: '8px',
    },
    statusBox: {
      backgroundColor: 'rgba(0, 32, 91, 0.85)',
      color: '#fff',
      padding: { xs: '5px 12px', sm: '6px 14px' },
      borderRadius: '12px',
      fontSize: { xs: '0.8rem', sm: '0.85rem' },
      fontWeight: 'bold',
      boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
      letterSpacing: '0.5px',
      marginTop: { xs: '8px', sm: '10px' },
      marginBottom: { xs: '5px', sm: '0' },
    },
  };